Brute force
Altu-Bitu-2/Altu-Bitu-AGStudy pull request #5
Opened 2022-03-23 11:21 UTC by peach1510

#### 내용 & 질문
> 1759 문제를 해결하기 위해 백트래킹으로 구현을 시도했는데 어느 부분에서 잘못된건지 모르겠습니다.
또, 이 방법이 아니라 단순 브루트포스로 구할 경우 어떤 방식으로 접근해야 하는지 궁금합니다. 감사합니다!

#### <기존 제출>
> 10757, 2503, 2798, 1018, 1759, 2858

#### <추가 제출>
> X

2022-03-24 15:58 UTC, ZERO-black approved these changes
필수 2/2문제, 선택 3/5문제 확인되셨습니다!
1759번 수정해보시고 저 다시 리뷰어로 호출해주세요!
어려운 부분 있으시면 더 질문하셔도 좋아요😊

2022-03-24 15:58 UTC, ZERO-black commented on 220318 브루트 포스/B1018.py
> +B = ['BWBWBWBW','WBWBWBWB','BWBWBWBW','WBWBWBWB','BWBWBWBW','WBWBWBWB','BWBWBWBW','WBWBWBWB']
p2. W와 B는 정확히 반대되네요. 이 점을 잘 이용하면 연산을 반으로 줄일 수 있어요!
p3. MAX, MIN과 같은 전역변수가 아닌 경우에는 변수 이름으로 대문자는 피해주시는게 좋아요😊

2022-03-24 15:58 UTC, ZERO-black commented on 220318 브루트 포스/B10757.py
> +    answer = result + result2
p2. 계산 하는 부분을 하나의 함수로 빼는게 코드가 더 깔끔하고 명확할거 같습니다.

2022-03-24 15:58 UTC, ZERO-black commented on 220318 브루트 포스/B1759.py
> +vowel = ['a', 'e', 'i', 'o', 'u']
p2. `set()`에 문자열을 인자로 주면 어떻게 될까요? 이걸 활용하면 코드를 좀 더 편하게 짤 수 있어요😊

2022-03-24 15:58 UTC, ZERO-black commented on 220318 브루트 포스/B2503.py
> +            count += 1
p2. 동일하지 않다면, 다음 질문에 대한 검사를 계속하는 것이 좋을까요?

2022-03-24 15:58 UTC, ZERO-black commented on 220318 브루트 포스/B2503.py
> +    for j in range(n):
p3. 지금 j 자체를 이용하고 있지 않죠, 이런 상황에서는 range를 쓰지 않고 바로 리스트를 for문으로 돌리면 변수가 줄어서 코딩하기도 편하고, 가독성도 좋아요!

2022-03-24 15:58 UTC, ZERO-black commented on 220318 브루트 포스/B2798.py
> +card = list(map(int, input().split()))
p2. 처음에 카드 숫자를 정렬하면, 계산하는 경우의 수를 조금 줄일 수 있어요!

2022-03-24 15:58 UTC, ZERO-black commented on 220318 브루트 포스/B2858.py
> +            x, y = y, x
p2. 현재 x의 범위를 생각해보세요! x와 y의 대소관계를 알 수 있어요.

2022-03-24 15:59 UTC, ZERO-black requested changes

2022-03-24 15:59 UTC, ZERO-black commented on 220318 브루트 포스/B1759.py
> +        return
p1. idx == c이면 바로 종료해야 할까요?

+) 프로그램이 생각대로 답이 나오지 않으면 중간과정을 출력해보면서 디버깅 하는 것도 방법이에요! 그래야 어느 부분에서 잘못되었는지 확인이 가능합니다!

2022-03-25 15:14 UTC, peach1510 commented
조언해 주신 부분들 수정해 코드를 개선했습니다. 항상 감사합니다! 몇 가지 의문이 있어 추가로 질문 드릴 수 있을까요? 😊
Q1. 1018에서 W와 B가 반대되는 점을 이용해 연산을 어떻게 줄일 수 있을지 생각나지 않습니다 ㅠㅠ!!)
Q2. 1759번 문제를 도움을 받아 해결했습니다. 감사합니다! 😍 다만 조언해주신 set()은 어떤 부분에 활용하면 좋을지 궁금합니다.

2022-03-25 15:48 UTC, ZERO-black commented
Q1. 어떤 보드를 W로 시작하는 체스판으로 만들 때랑 정확히 반대로 하면 B로 시작하는 체스판을 만들 수 있어요!
Q2. `set("aeiou")` 이런식으로 셋을 선언/초기화 할 수 있습니다!

2022-03-26 05:17 UTC, peach1510 commented
말씀해주신 부분과 풀이 코드 참조하여 수정했습니다. 감사합니다! 🥺

2022-03-26 09:44 UTC, merged